runTomeCanoUser:
	python3 Programa.py ./Data/TomeCano.csv 1 
runTomeCanoServer:
	python3 Programa.py ./Data/TomeCano.csv 0 1 12 1 1 ./FinalImage.png
runCoronavirusUser:
	python3 Programa.py ./Data/Coronavirus-04-06-2020.csv 1
runCoronavirusServer:
	python3 Programa.py ./Data/Coronavirus-04-06-2020.csv 0 3 7 1 1 ./FinalImage.png
runCoronavirusPaisUser:
	python3 Programa.py ./Data/Coronavirus-Paises.csv 1
runCoronavirusPaisServer:
	python3 Programa.py ./Data/Coronavirus-Paises.csv 0 1 4/13/20,4/14/20,4/15/20,4/16/20,4/17/20 0 1 1 1 Canada,Argentina,China,France,Germany,Spain,US ./FinalImage.png