runTomeCanoUser:
	python3 Programa.py ./Data/TomeCano.csv 1 
runTomeCanoServer:
	python3 Programa.py ./Data/TomeCano.csv 0 1 12 1 1 ./FinalImage.png
runCoronavirusUser:
	python3 Programa.py ./Data/Coronavirus-04-06-2020.csv 1
runCoronavirusServer:
	python3 Programa.py ./Data/Coronavirus-04-06-2020.csv 0 3 7 1 1 ./FinalImage.png