runNatalidadUser:
	python3 Programa.py ./Data/natalidad.geojson 1 
runNatalidadServer:
	python3 Programa.py ./Data/natalidad.geojson 0 14 NAT2018 0 0 0 0 0 ./image.png
runAccidentesUser:
	python3 Programa.py ./Data/Accidentes_2016.csv 1 
runAccidentesServer:
	python3 Programa.py ./Data/Accidentes_2016.csv 0 1 ACCIDENTES_CON_VICTIMAS_EN_VIAS,ACCIDENTES_MORTALES_EN_VIAS_INT,FALLECIDOS_VIAS_INTERURBANAS,HERIDOS_HOSPITALIZADOS_EN_VIAS_,ACCIDENTES_MORTALES_EN_VIAS_URB,FALLECIDOS_VIAS_URBANAS 0 2 1 2 Santa_Cruz_de_Tenerife,Las_Palmas ./FinalImage.png
runAlmacenUser:
	python3 Programa.py ./Data/Prueba.json 1 
runTomeCanoUser:
	python3 Programa.py ./Data/TomeCano.csv 1 
runTomeCanoServer:
	python3 Programa.py ./Data/TomeCano.csv 0 1 12 1 1 ./FinalImage.png
runCoronavirusUser:
	python3 Programa.py ./Data/Coronavirus-04-06-2020.csv 1
runCoronavirusServer:
	python3 Programa.py ./Data/Coronavirus-04-06-2020.csv 0 3 7 1 1 ./FinalImage.png
runCoronavirusPaisUser:
	python3 Programa.py ./Data/Coronavirus-Paises.csv 1
runCoronavirusPaisServer:
	python3 Programa.py ./Data/Coronavirus-Paises.csv 0 1 4/10/20,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20 0 1 1 1 France,Spain,Italy ./FinalImage.png